package com.example.openglstudydemo

/**
 * 视频类型的枚举
 */
enum class VideoTypeEnum {
    SIMPLE_YUV,
    NO_FILTER_YUV,
    GRAY_FILTER_YUV,
    OPPO_FILTER_YUV,
    DIVIDE_TO_2_YUV,
    DIVIDE_TO_4_YUV,
    SOUL_FLY_OFF_YUV,
    GAUSS_BLUR_YUV,
    DRAW_TRIANGLE,
    DRAW_TRIANGLE_UNIFORM,
    DRAW_TRIANGLE_VBO,
    DRAW_TRIANGLE_EBO,
    DRAW_TWO_TRIANGLE,
    DRAW_LINE,
    DRAW_TEXTURE_MAX,
    DRAW_3D_TEXTURE,
    DRAW_3D_CUBE_TEXTURE,
    DRAW_GRADIENT_COLOR_CUBE_TEXTURE,
    DRAW_CUBES_MOVE_CAMERA,
}